services:
  frontend:
    build: .
    ports:
        - 80:8000

  backend:
    build: .
    ports:
        - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DanielDBPassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: