version: '3'
services:
  web:
    build: .
    ports:
      - "5432:5432"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DanielDBPassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
  
