services:
  frontend:
    build: ./Frontend
    ports:
        - 8000:80

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: DanielDBPassword
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
        
  backend:
    build: 
      context: ./Backend
    depends_on:
      - db
    ports:
        - 8080:8080
  
volumes:
  pgdata: