version: '3'
services:
  web:
    build: .
    ports:
      - "5432:5432"
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRESQL_PASSWORD=DanielDBPassword
    ports:
      - "8080:8080"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  
volumes:
  postgres_db:
    driver: local
