services:
  frontend:
    build: ./Frontend
    ports:
        - 8000:80

  web:
    container_name: web
    build: ./Backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  
volumes:
  pgdata:
