version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "postgresql"
    environment:
      POSTGRESQL_PASSWORD: SomethingHere
    volumes:
      - db-data:/foo
  
  volumes:
    db-data:
