version: '3'
services:
  web:
    build: .
    ports:
        - 80:8000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DanielDBPassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
# This isn't edited at all.