export const prompts = [
    {prompt: "What is the capital of France?", response: "The capital of France is Paris.", image: "paris.jpg", rating: 4.5, approved: true, llmName: "Bard", createdAt: "2024-04-02T12:00:00Z", summary: "The Capital of France", title: "Capital of France"},
    {prompt: "Explain the theory of relativity.", response: "The theory of relativity describes how objects in motion experience time and space differently.", image: "relativity.jpg", rating: 4.7, approved: true, llmName: "ChatGPT", createdAt: "2024-04-02T12:00:00Z", summary: "Theory of Relativity", title: "Theory of Relativity"},
    {prompt: "Who painted the Mona Lisa?", response: "The Mona Lisa was painted by Leonardo da Vinci.", image: "mona_lisa.jpg", rating: 4.8, approved: true, llmName: "CoPilot", createdAt: "2024-04-02T12:00:00Z", summary: "Painter of the Mona Lisa", title: "Painter of the Mona Lisa"},
    {prompt: "What is the significance of the Industrial Revolution?", response: "The Industrial Revolution marked a major turning point in history, leading to significant advancements in technology, industry, and society.", image: "industrial_revolution.jpg", rating: 4.9, approved: true, llmName: "Bard", createdAt: "2024-04-02T12:00:00Z", summary: "Significance of Industrial Revolution", title: "Significance of Industrial Revolution"},
    {prompt: "Who wrote \"To Kill a Mockingbird\"?", response: "\"To Kill a Mockingbird\" was written by Harper Lee.", image: "to_kill_a_mockingbird.jpg", rating: 4.6, approved: true, llmName: "ChatGPT", createdAt: "2024-04-02T12:00:00Z", summary: "Author of To Kill a Mockingbird", title: "Author of To Kill a Mockingbird"},
    {prompt: "Explain the process of photosynthesis.", response: "Photosynthesis is the process by which plants convert light energy into chemical energy to fuel their growth and development.", image: "photosynthesis.jpg", rating: 4.7, approved: true, llmName: "CoPilot", createdAt: "2024-04-02T12:00:00Z", summary: "Process of Photosynthesis", title: "Process of Photosynthesis"},
    {prompt: "What are the key features of Baroque art?", response: "Baroque art is characterized by its dramatic use of light and shadow, grandeur, and emotional intensity.", image: "baroque.jpg", rating: 4.8, approved: true, llmName: "Bard", createdAt: "2024-04-02T12:00:00Z", summary: "Features of Baroque Art", title: "Features of Baroque Art"},
    {prompt: "Who discovered penicillin?", response: "Penicillin was discovered by Alexander Fleming.", image: "penicillin.jpg", rating: 4.9, approved: true, llmName: "ChatGPT", createdAt: "2024-04-02T12:00:00Z", summary: "Discoverer of Penicillin", title: "Discoverer of Penicillin"},
    {prompt: "What is the significance of the Magna Carta?", response: "The Magna Carta is considered one of the most important documents in history as it established the principle that everyone, including the king, is subject to the law.", image: "magna_carta.jpg", rating: 4.8, approved: true, llmName: "CoPilot", createdAt: "2024-04-02T12:00:00Z", summary: "Significance of Magna Carta", title: "Significance of Magna Carta"},
    {prompt: "What are the main themes in \"1984\" by George Orwell?", response: "\"1984\" explores themes of totalitarianism, surveillance, censorship, and the loss of individuality.", image: "1984.jpg", rating: 4.7, approved: true, llmName: "Bard", createdAt: "2024-04-02T12:00:00Z", summary: "Themes in 1984", title: "Themes in 1984"}
];